"""empty message

Revision ID: 9365f438dea3
Revises: 
Create Date: 2022-11-27 01:02:29.818496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9365f438dea3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentalService',
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('websiteLink', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('serviceId')
    )
    op.create_table('reservation',
    sa.Column('reservId', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reservId')
    )
    op.create_table('administrator',
    sa.Column('idAdministrator', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('RentalService_serviceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RentalService_serviceId'], ['rentalService.serviceId'], ),
    sa.PrimaryKeyConstraint('idAdministrator')
    )
    op.create_table('car',
    sa.Column('carId', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=45), nullable=False),
    sa.Column('model', sa.String(length=45), nullable=False),
    sa.Column('maxSpeed', sa.Integer(), nullable=False),
    sa.Column('yearProduction', sa.Integer(), nullable=False),
    sa.Column('fuelConsumption', sa.Integer(), nullable=False),
    sa.Column('seatsNumber', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('Reservation_reservId', sa.Integer(), nullable=True),
    sa.Column('RentalService_serviceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RentalService_serviceId'], ['rentalService.serviceId'], ),
    sa.ForeignKeyConstraint(['Reservation_reservId'], ['reservation.reservId'], ),
    sa.PrimaryKeyConstraint('carId')
    )
    op.create_table('passenger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('passwortNumber', sa.Integer(), nullable=False),
    sa.Column('passwortSeries', sa.String(length=5), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('RentalService_serviceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RentalService_serviceId'], ['rentalService.serviceId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passenger')
    op.drop_table('car')
    op.drop_table('administrator')
    op.drop_table('reservation')
    op.drop_table('rentalService')
    # ### end Alembic commands ###
